name: Release packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        default: 'patch'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.6.12
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@codota'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Version
        run: pnpm version ${{ inputs.version }}
      - name: Publish to NPM
        run: pnpm version patch && git push && git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
